using Microsoft.EntityFrameworkCore;

namespace ScheduleCollege.Web.Data;

public static class SchemaUpdater
{
    public static void Update(AppDbContext db)
    {
        var provider = db.Database.ProviderName ?? "";

        if (provider.Contains("Sqlite", StringComparison.OrdinalIgnoreCase))
        {
            TryExecute(db, "CREATE TABLE IF NOT EXISTS SystemSettings (Id INTEGER NOT NULL CONSTRAINT PK_SystemSettings PRIMARY KEY AUTOINCREMENT, Key TEXT NOT NULL, Value TEXT NOT NULL DEFAULT '');");
            TryExecute(db, "CREATE UNIQUE INDEX IF NOT EXISTS IX_SystemSettings_Key ON SystemSettings (Key);");

            TryExecute(db, "CREATE TABLE IF NOT EXISTS GroupStudyDays (Id INTEGER NOT NULL CONSTRAINT PK_GroupStudyDays PRIMARY KEY AUTOINCREMENT, StudyDate TEXT NOT NULL, GroupId INTEGER NOT NULL, StartPairNumber INTEGER NOT NULL DEFAULT 1, EndPairNumber INTEGER NOT NULL DEFAULT 6, IsDayOff INTEGER NOT NULL DEFAULT 0, Comment TEXT NOT NULL DEFAULT '', CONSTRAINT FK_GroupStudyDays_Groups_GroupId FOREIGN KEY (GroupId) REFERENCES Groups (Id) ON DELETE CASCADE);");
            TryExecute(db, "CREATE UNIQUE INDEX IF NOT EXISTS IX_GroupStudyDays_StudyDate_GroupId ON GroupStudyDays (StudyDate, GroupId);");
            TryExecute(db, "CREATE INDEX IF NOT EXISTS IX_GroupStudyDays_GroupId ON GroupStudyDays (GroupId);");

            AddColumnIfMissingSqlite(db, "ScheduleEntries", "Note", "TEXT NOT NULL DEFAULT ''");
            AddColumnIfMissingSqlite(db, "Teachers", "UnavailableDays", "TEXT NOT NULL DEFAULT ''");
            AddColumnIfMissingSqlite(db, "Rooms", "Format", "TEXT NOT NULL DEFAULT 'Очная'");
            AddColumnIfMissingSqlite(db, "Rooms", "OnlineLink", "TEXT NOT NULL DEFAULT ''");
            AddColumnIfMissingSqlite(db, "Users", "GroupCode", "TEXT NOT NULL DEFAULT ''");
            return;
        }

        if (provider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
        {
            TryExecute(db, "CREATE TABLE IF NOT EXISTS \"SystemSettings\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"Key\" character varying(100) NOT NULL, \"Value\" character varying(200) NOT NULL DEFAULT '');");
            TryExecute(db, "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_SystemSettings_Key\" ON \"SystemSettings\" (\"Key\");");

            TryExecute(db, "CREATE TABLE IF NOT EXISTS \"GroupStudyDays\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"StudyDate\" timestamp without time zone NOT NULL, \"GroupId\" integer NOT NULL, \"StartPairNumber\" integer NOT NULL DEFAULT 1, \"EndPairNumber\" integer NOT NULL DEFAULT 6, \"IsDayOff\" boolean NOT NULL DEFAULT false, \"Comment\" character varying(200) NOT NULL DEFAULT '', CONSTRAINT \"FK_GroupStudyDays_Groups_GroupId\" FOREIGN KEY (\"GroupId\") REFERENCES \"Groups\" (\"Id\") ON DELETE CASCADE);");
            TryExecute(db, "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_GroupStudyDays_StudyDate_GroupId\" ON \"GroupStudyDays\" (\"StudyDate\", \"GroupId\");");
            TryExecute(db, "CREATE INDEX IF NOT EXISTS \"IX_GroupStudyDays_GroupId\" ON \"GroupStudyDays\" (\"GroupId\");");

            TryExecute(db, "ALTER TABLE \"ScheduleEntries\" ADD COLUMN \"Note\" character varying(200) NOT NULL DEFAULT '';");
            TryExecute(db, "ALTER TABLE \"Teachers\" ADD COLUMN \"UnavailableDays\" character varying(200) NOT NULL DEFAULT '';");
            TryExecute(db, "ALTER TABLE \"Rooms\" ADD COLUMN \"Format\" character varying(20) NOT NULL DEFAULT 'Очная';");
            TryExecute(db, "ALTER TABLE \"Rooms\" ADD COLUMN \"OnlineLink\" character varying(200) NOT NULL DEFAULT '';");
            TryExecute(db, "ALTER TABLE \"Users\" ADD COLUMN \"GroupCode\" character varying(30) NOT NULL DEFAULT '';");
            return;
        }

        if (provider.Contains("MySql", StringComparison.OrdinalIgnoreCase)
            || provider.Contains("Pomelo", StringComparison.OrdinalIgnoreCase))
        {
            TryExecute(db, "CREATE TABLE IF NOT EXISTS SystemSettings (Id int NOT NULL AUTO_INCREMENT PRIMARY KEY, `Key` varchar(100) NOT NULL, Value varchar(200) NOT NULL DEFAULT '');");
            TryExecute(db, "CREATE UNIQUE INDEX IX_SystemSettings_Key ON SystemSettings (`Key`);");

            TryExecute(db, "CREATE TABLE IF NOT EXISTS GroupStudyDays (Id int NOT NULL AUTO_INCREMENT PRIMARY KEY, StudyDate datetime(6) NOT NULL, GroupId int NOT NULL, StartPairNumber int NOT NULL DEFAULT 1, EndPairNumber int NOT NULL DEFAULT 6, IsDayOff tinyint(1) NOT NULL DEFAULT 0, Comment varchar(200) NOT NULL DEFAULT '', CONSTRAINT FK_GroupStudyDays_Groups_GroupId FOREIGN KEY (GroupId) REFERENCES `Groups` (Id) ON DELETE CASCADE);");
            TryExecute(db, "CREATE UNIQUE INDEX IX_GroupStudyDays_StudyDate_GroupId ON GroupStudyDays (StudyDate, GroupId);");
            TryExecute(db, "CREATE INDEX IX_GroupStudyDays_GroupId ON GroupStudyDays (GroupId);");

            TryExecute(db, "ALTER TABLE ScheduleEntries ADD COLUMN Note varchar(200) NOT NULL DEFAULT '';");
            TryExecute(db, "ALTER TABLE Teachers ADD COLUMN UnavailableDays varchar(200) NOT NULL DEFAULT '';");
            TryExecute(db, "ALTER TABLE Rooms ADD COLUMN Format varchar(20) NOT NULL DEFAULT 'Очная';");
            TryExecute(db, "ALTER TABLE Rooms ADD COLUMN OnlineLink varchar(200) NOT NULL DEFAULT '';");
            TryExecute(db, "ALTER TABLE Users ADD COLUMN GroupCode varchar(30) NOT NULL DEFAULT '';");
        }
    }

    private static void AddColumnIfMissingSqlite(AppDbContext db, string tableName, string columnName, string columnSql)
    {
        var connection = db.Database.GetDbConnection();

        if (connection.State != System.Data.ConnectionState.Open)
        {
            connection.Open();
        }

        var columns = new List<string>();

        using (var command = connection.CreateCommand())
        {
            command.CommandText = $"PRAGMA table_info({tableName});";

            using var reader = command.ExecuteReader();

            while (reader.Read())
            {
                columns.Add(reader["name"].ToString() ?? "");
            }
        }

        if (columns.Count == 0)
        {
            return;
        }

        if (columns.Any(x => string.Equals(x, columnName, StringComparison.OrdinalIgnoreCase)))
        {
            return;
        }

        db.Database.ExecuteSqlRaw($"ALTER TABLE {tableName} ADD COLUMN {columnName} {columnSql};");
    }

    private static void TryExecute(AppDbContext db, string sql)
    {
        try
        {
            db.Database.ExecuteSqlRaw(sql);
        }
        catch
        {
            // Если таблица, индекс или колонка уже есть, запуск приложения не останавливаем.
        }
    }
}
